import Dexie, { type Table } from 'dexie';

export interface Product {
  id: string;
  name: string;
  aliases: string[];
  category: string;
  stock: number;
  unit: string;
  costPrice: number;
  sellingPrice: number;
  lowStockThreshold: number;
  expiryDate?: string;
  parentId?: string;
  deleted?: boolean;
  isVaccine?: boolean;
  batches?: Batch[];
}

export interface Batch {
  id: string;
  batchNumber: string;
  expiryDate: string;
  quantity: number;
  receivedDate: string;
  temperatureLogs?: TemperatureLog[];
}

export interface TemperatureLog {
  timestamp: number;
  temp: number;
  status: 'optimal' | 'warning' | 'critical';
}

export interface Transaction {
  id: string;
  type: 'sale' | 'purchase' | 'adjustment' | 'bulk-break';
  productId: string;
  productName: string;
  quantity: number;
  amount: number;
  profit: number;
  paymentMethod: 'cash' | 'mpesa' | 'airtel' | 'credit' | 'bank';
  paymentStatus: 'paid' | 'pending';
  customerId?: string;
  customerName?: string;
  timestamp: number;
  performedBy: string;
  synced: boolean;
  deleted?: boolean;
  batchId?: string;
  taxQrCode?: string; // eTIMS/URA
  commissionEarned?: number;
  isSubsidy?: boolean;
  carbonCredits?: number;
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  totalDebt: number;
  creditLimit: number;
  lastTransaction: number;
  riskLevel: 'low' | 'medium' | 'high';
  collateral?: Collateral[];
  chamaId?: string;
  gpsLocation?: string;
}

export interface Collateral {
  id: string;
  type: 'Land' | 'Livestock' | 'Vehicle' | 'Equipment' | 'Other';
  description: string;
  estimatedValue: number;
  gpsTag?: string;
  photoUrl?: string;
}

export interface Chama {
  id: string;
  name: string;
  members: string[]; // Customer IDs
  totalLiability: number;
}

export interface PurchaseOrder {
  id: string;
  supplierName: string;
  items: { productId: string; quantity: number; cost: number }[];
  status: 'draft' | 'sent' | 'received';
  timestamp: number;
  isAutoGenerated: boolean;
}

export interface SyncQueueItem {
  id?: number;
  action: 'create' | 'update' | 'delete';
  collection: string;
  data: any;
  timestamp: number;
}

export class AgroFlowDB extends Dexie {
  products!: Table<Product>;
  transactions!: Table<Transaction>;
  customers!: Table<Customer>;
  chamas!: Table<Chama>;
  purchaseOrders!: Table<PurchaseOrder>;
  syncQueue!: Table<SyncQueueItem>;

  constructor() {
    super('AgroFlowDB');
    this.version(2).stores({
      products: 'id, name, *aliases, category, expiryDate',
      transactions: 'id, type, productId, customerId, timestamp, synced',
      customers: 'id, name, phone, riskLevel, chamaId',
      chamas: 'id, name',
      purchaseOrders: 'id, supplierName, status',
      syncQueue: '++id, collection, timestamp'
    });
  }
}

export const db = new AgroFlowDB();
